version: '3.8'

networks:
  app-network:
    external: false

services:
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    restart: always
    ports:
      - "50052:50052"
    networks:
      - app-network
    depends_on:
      - kafka
      - admin